spring:
  application.name: hystrix-monitor
server:
  port: 8900
turbine:
  combine-host-port: true
  # 配置需要监控的服务名称列表
  app-config: API-GATEWAY-SERVER,GATEWAY-EUREKA-CONSUMER,GATEWAY-EUREKA-PROVIDER,GATEWAY-EUREKA-SERVER
  cluster-name-expression: "'default'"
  aggregator:
    cluster-config: default
  #instanceUrlSuffix: /actuator/hystrix.stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/